### ISSUE TITLE
Detail

### ISSUE THREAD

**Issue by yaani** [ghztomash/MIDI-Rotary-Encoder#1]
Pls add details  to this code as ther are errors appearing when i try ro compile it.
 These are:

In file included from newRotaryEncoder_MIDI.ino:5:
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:10:22: error: WProgram.h: No such file or directory
In file included from newRotaryEncoder_MIDI.ino:5:
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:14: error: ISO C++ forbids declaration of 'uint16_t' with no type
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:14: error: expected ';' before '_' token
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:15: error: ISO C++ forbids declaration of 'uint16_t' with no type
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:15: error: expected ';' before '_' token
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:16: error: 'byte' does not name a type
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:17: error: 'byte' does not name a type
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:18: error: 'byte' does not name a type
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:19: error: 'byte' does not name a type
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:20: error: 'byte' does not name a type
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:21: error: 'byte' does not name a type
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:22: error: 'byte' does not name a type
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:23: error: 'byte' does not name a type
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:25: error: expected `)' before 'sdiPin'
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:28: error: 'byte' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:28: error: 'uint16_t' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:29: error: 'byte' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:29: error: 'byte' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:29: error: 'boolean' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:30: error: 'byte' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:30: error: 'boolean' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:31: error: 'byte' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:32: error: 'byte' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:33: error: 'byte' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:33: error: 'uint16_t' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:34: error: 'byte' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:34: error: 'byte' has not been declared
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:34: error: 'uint16_t' has not been declared
newRotaryEncoder_MIDI:30: error: no matching function for call to 'ledRings::ledRings(int, int, int, int, int)'
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:12: note: candidates are: ledRings::ledRings()
C:\Program Files (x86)\Arduino\libraries\ledRings/ledRings.h:12: note:                 ledRings::ledRings(const ledRings&)
newRotaryEncoder_MIDI:31: error: 'Encoder' does not name a type
newRotaryEncoder_MIDI:32: error: 'Encoder' does not name a type
newRotaryEncoder_MIDI:33: error: 'Encoder' does not name a type
newRotaryEncoder_MIDI:34: error: 'Encoder' does not name a type
newRotaryEncoder_MIDI:40: error: expected constructor, destructor, or type conversion before '*' token
newRotaryEncoder_MIDI.ino: In function 'void setup()':
newRotaryEncoder_MIDI:59: error: 'usbMIDI' was not declared in this scope
newRotaryEncoder_MIDI:65: error: 'buttonState' was not declared in this scope
newRotaryEncoder_MIDI:65: error: expected type-specifier before 'Bounce'
newRotaryEncoder_MIDI:65: error: expected`;' before 'Bounce'
newRotaryEncoder_MIDI.ino: In function 'void loop()':
newRotaryEncoder_MIDI:80: error: 'usbMIDI' was not declared in this scope
newRotaryEncoder_MIDI:84: error: 'knob1' was not declared in this scope
newRotaryEncoder_MIDI:85: error: 'knob2' was not declared in this scope
newRotaryEncoder_MIDI:86: error: 'knob3' was not declared in this scope
newRotaryEncoder_MIDI:87: error: 'knob4' was not declared in this scope
newRotaryEncoder_MIDI:93: error: 'usbMIDI' was not declared in this scope
newRotaryEncoder_MIDI:97: error: 'buttonState' was not declared in this scope
newRotaryEncoder_MIDI:129: error: 'usbMIDI' was not declared in this scope
newRotaryEncoder_MIDI.ino: In function 'void ledInitialize()':
newRotaryEncoder_MIDI:142: error: 'class ledRings' has no member named 'num_leds_arc'
newRotaryEncoder_MIDI:149: error: 'class ledRings' has no member named 'num_leds_arc'
newRotaryEncoder_MIDI.ino: In function 'void midiCC(int, int)':
newRotaryEncoder_MIDI:180: error: 'usbMIDI' was not declared in this scope
newRotaryEncoder_MIDI:184: error: 'usbMIDI' was not declared in this scope
newRotaryEncoder_MIDI:192: error: 'usbMIDI' was not declared in this scope
newRotaryEncoder_MIDI:196: error: 'usbMIDI' was not declared in this scope

**Comment by ghztomash** [comment]
Hi,
Do you have the Encoder and LedRings libraries installed correctly?
What version of teensyduino are you using? 
Did you enable USB MIDI?

**Comment by yaani** [comment]
i do have libraries installed properly. I followed your link and downloaded and pasted in libraries. while i am using arduino uno. i have no idea od this teensyduino and usb midi

**Comment by ghztomash** [comment]
Unfortunately this code does not work as it is with an Arduino but only with the Teensy chips.
